import type { GameSettings, Story } from './types';

// A simple UUID generator that is compatible with all browsers, including insecure contexts (http).
export const simpleUUID = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = (Math.random() * 16) | 0,
      v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

export const translations = {
  en: {
    title: "Gemini Adventure",
    description: "An epic text adventure where the story and visuals are crafted in real-time by AI. Every choice you make creates a new world.",
    errorTitle: "An Error Occurred",
    startNewGame: "Start New Game",
    back: "Back",
    actionsHeader: "What do you do next?",
    actionsHeaderNext: "Next:",
    actionSay: "Say",
    actionDo: "Do",
    actionHappened: "Happened",
    sayActionFormat: `{user} says, "{action}"`,
    placeholderSay: "Say something...",
    placeholderDo: "Do something...",
    placeholderHappened: "Describe what happened...",
    awaitingNextChapter: "Awaiting the next chapter...",
    scenePlaceholder: "Your story awaits...",
    loadingMessages: [
      "The world is changing...",
      "Crafting your fate...",
      "Weaving the threads of destiny...",
      "The cosmos holds its breath...",
      "Painting the scene...",
    ],
    backgroundLabel: "Background Setting",
    backgroundPlaceholder: "e.g., A forgotten kingdom cursed with eternal twilight, where ancient ruins hide powerful artifacts. You can use {{user}} and {{char}} as placeholders.",
    characterLabel: "Character Details",
    characterPlaceholder: "e.g., A disgraced knight named {{user}} seeking redemption, haunted by visions of a fallen queen named {{char}}.",
    openingMonologueLabel: "Opening Monologue",
    openingMonologuePlaceholder: "e.g., You are a master storyteller. Provide a detailed and atmospheric opening monologue that sets the stage for the dark fantasy adventure. This is spoken to the player before their first action.",
    openingActionLabel: "Opening Action",
    openingActionPlaceholder: "e.g., Start a new adventure game in a dark fantasy world. Provide the opening scene for {{user}}.",
    importGame: "Load Game",
    exportGame: "Save Game",
    settings: "Settings",
    summariesHeader: "Story Log",
    llmSettings: "LLM Settings",
    gameSettings: "Game Settings",
    systemInstructions: "System Instructions",
    addInstruction: "Add Instruction",
    temperature: "Temperature",
    topP: "Top-P",
    topK: "Top-K",
    maxTokens: "Max Tokens",
    storyLog: "Story Log",
    debugLog: "Debug Log",
    close: "Close",
    startAdventure: "Start Adventure",
    frequencyPenalty: "Frequency Penalty",
    presencePenalty: "Presence Penalty",
    resetToDefaults: "Reset to Defaults",
    regenerate: "Regenerate",
    editInstruction: "Edit Instruction",
    instructionTitle: "Title",
    instructionTitlePlaceholder: "e.g., Game Master Persona",
    instructionRole: "Role",
    instructionPrompt: "Prompt",
    save: "Save",
    cancel: "Cancel",
    send: "Send",
    stop: "Stop",
    namePlaceholders: "Name Your Characters",
    nameUser: "Your Name",
    nameUserPlaceholder: "Enter the protagonist's name",
    nameChar: "Character Name",
    nameCharPlaceholder: "Enter another key character's name",
    confirm: "Confirm",
    autoMaxTokens: "Auto-fetch",
    fetchedTokens: "Fetched:",
    // Platform Translations
    navHome: "Home",
    navExplore: "Explore",
    navCreate: "Create",
    navProfile: "Profile",
    navGame: "Game",
    exploreSearchPlaceholder: "Search for stories...",
    createTitle: "Create a New Story",
    editTitle: "Edit Story",
    publish: "Publish",
    tabBasicInfo: "Basic Info",
    tabLibrary: "Library",
    tabPlotSettings: "Plot Settings",
    storyTitle: "Title",
    storyTitlePlaceholder: "Enter your story's title",
    storyDescription: "Story Description",
    storyDescriptionPlaceholder: "A brief, enticing summary of your adventure.",
    coverImageURL: "Cover Image URL",
    coverImageURLPlaceholder: "https://example.com/image.png",
    visibility: "Visibility",
    visibilityPublic: "Public",
    visibilityPrivate: "Private",
    category: "Category",
    categoryPlaceholder: "e.g., Fantasy, Sci-Fi, Mystery",
    libraryHeader: "Library Cards",
    addLibraryCard: "Add Card",
    editCard: "Edit Card",
    cardName: "Name",
    cardType: "Type",
    cardContent: "Content (AI Instructions)",
    cardKeywords: "Keywords",
    keywordsPlaceholder: "e.g., rogue, mysterious, locket",
    cardTypeCharacter: "Character",
    cardTypeLocation: "Location",
    cardTypeItem: "Item",
    cardTypeQuest: "Quest",
    cardTypeSetting: "Setting",
    cardTypeCustom: "Custom",
    customTypeName: "Custom Type Name",
    allCategories: "All",
    openingSpeaker: "Opening Speaker",
    narrator: "Narrator",
    backgroundSetting: "Background Setting",
    insertReference: "Insert",
    characterCount: "Character Count",
    deleteCard: "Delete Card",
    myStories: "My Stories",
    recentlyPlayed: "Recently Played",
    continue: "Continue",
    deleteProgress: "Delete Progress",
    noStoriesCreated: "You haven't created any stories yet.",
    createFirstStory: "Create your first adventure!",
    noGamesPlayed: "You haven't played any stories yet.",
    findAStory: "Find a story to play!",
    dialogueWindowOpacity: "Dialogue Window Opacity",
    dialogueBubbleOpacity: "Dialogue Bubble Opacity",
    // Dialogs
    discardChangesTitle: "Discard Changes?",
    discardChangesMessage: "You have unsaved changes. Are you sure you want to exit? To save your work in progress, you can publish it as 'Private'.",
    discard: "Discard",
    keepEditing: "Keep Editing",
    deleteCardTitle: "Delete Library Card?",
    deleteCardMessage: "Are you sure you want to permanently delete this card? This action cannot be undone.",
    delete: "Delete",
    edit: "Edit",
    import: "Import",
    export: "Export",
    publishErrorTitle: "Cannot Publish",
    publishErrorMessage: "Please fill in the Title, Story Description, and Opening Monologue before publishing.",
    restartGameTitle: "Restart Adventure?",
    restartGameMessage: "Are you sure you want to start a new game? Your current progress in this adventure will be lost.",
    restart: "Restart",
    deleteStoryTitle: "Delete Story?",
    deleteStoryMessage: "Are you sure you want to permanently delete this story? All saved progress will also be lost. This action cannot be undone.",
    deletePlaythroughTitle: "Delete Progress?",
    deletePlaythroughMessage: "Are you sure you want to delete your saved progress for this story? This action cannot be undone.",
  },
  zh: {
    title: "Gemini 冒险",
    description: "一个史诗般的文字冒险游戏，故事和视觉效果都由人工智能实时制作。你的每一个选择都会创造一个新世界。",
    errorTitle: "发生错误",
    startNewGame: "开始新游戏",
    back: "返回",
    actionsHeader: "接下来你做什么？",
    actionsHeaderNext: "接下来：",
    actionSay: "说",
    actionDo: "做",
    actionHappened: "发生了",
    sayActionFormat: `{user} 说: "{action}"`,
    placeholderSay: "说什么...",
    placeholderDo: "做什么...",
    placeholderHappened: "描述发生的事情...",
    awaitingNextChapter: "等待下一章...",
    scenePlaceholder: "你的故事正在等待...",
    loadingMessages: [
      "世界正在改变...",
      "塑造你的命运...",
      "编织命运之线...",
      "宇宙屏住了呼吸...",
      "描绘场景...",
    ],
    backgroundLabel: "背景设定",
    backgroundPlaceholder: "例如：一个被永恒黄昏诅咒的被遗忘的王国，古老的废墟中隐藏着强大的神器。你可以使用 {{user}} 和 {{char}} 作为占位符。",
    characterLabel: "人物设定",
    characterPlaceholder: "例如：一位名叫 {{user}} 的蒙羞骑士寻求救赎，被一位名叫 {{char}} 的堕落女王的幻象所困扰。",
    openingMonologueLabel: "开场白",
    openingMonologuePlaceholder: "例如：你是一位讲故事的大师。提供一段详细且富有感染力的开场白，为这场黑暗幻想冒险奠定基调。这段话会在玩家采取第一个行动前对他/她说。",
    openingActionLabel: "开场选项",
    openingActionPlaceholder: "例如：为 {{user}} 开始一个黑暗幻想世界的文字冒险游戏。请提供开场场景。",
    importGame: "读取游戏",
    exportGame: "保存游戏",
    settings: "设置",
    summariesHeader: "故事日志",
    llmSettings: "LLM 设置",
    gameSettings: "游戏设置",
    systemInstructions: "系统提示词",
    addInstruction: "添加提示词",
    temperature: "温度",
    topP: "Top-P",
    topK: "Top-K",
    maxTokens: "最大令牌数",
    storyLog: "故事日志",
    debugLog: "调试日志",
    close: "关闭",
    startAdventure: "开始冒险",
    frequencyPenalty: "频率惩罚",
    presencePenalty: "存在惩罚",
    resetToDefaults: "重置为默认值",
    regenerate: "重新生成",
    editInstruction: "编辑提示词",
    instructionTitle: "标题",
    instructionTitlePlaceholder: "例如：游戏大师角色",
    instructionRole: "角色",
    instructionPrompt: "提示词",
    save: "保存",
    cancel: "取消",
    send: "发送",
    stop: "停止",
    namePlaceholders: "为你的角色命名",
    nameUser: "你的名字",
    nameUserPlaceholder: "输入主角的名字",
    nameChar: "角色名字",
    nameCharPlaceholder: "输入另一个关键角色的名字",
    confirm: "确认",
    autoMaxTokens: "自动获取",
    fetchedTokens: "已获取:",
    // Platform Translations
    navHome: "主页",
    navExplore: "分类",
    navCreate: "创作",
    navProfile: "我",
    navGame: "临时",
    exploreSearchPlaceholder: "搜索故事...",
    createTitle: "创作新故事",
    editTitle: "编辑故事",
    publish: "发布",
    tabBasicInfo: "基本信息",
    tabLibrary: "资料库",
    tabPlotSettings: "剧情设定",
    storyTitle: "标题",
    storyTitlePlaceholder: "输入你的故事标题",
    storyDescription: "故事简介",
    storyDescriptionPlaceholder: "一个简短、吸引人的冒险摘要。",
    coverImageURL: "封面图片 URL",
    coverImageURLPlaceholder: "https://example.com/image.png",
    visibility: "可见性",
    visibilityPublic: "公开",
    visibilityPrivate: "非公开",
    category: "分类",
    categoryPlaceholder: "例如：幻想、科幻、悬疑",
    libraryHeader: "资料卡",
    addLibraryCard: "添加资料卡",
    editCard: "编辑资料卡",
    cardName: "名字",
    cardType: "类别",
    cardContent: "内容（AI 指令）",
    cardKeywords: "关键字",
    keywordsPlaceholder: "例如：盗贼, 神秘, 挂坠",
    cardTypeCharacter: "角色",
    cardTypeLocation: "地点",
    cardTypeItem: "道具",
    cardTypeQuest: "任务",
    cardTypeSetting: "设定",
    cardTypeCustom: "自定义",
    customTypeName: "自定义类别名称",
    allCategories: "全部",
    openingSpeaker: "开场白发言人",
    narrator: "旁白",
    backgroundSetting: "背景设定",
    insertReference: "插入",
    characterCount: "字数统计",
    deleteCard: "删除资料卡",
    myStories: "我的故事",
    recentlyPlayed: "最近游玩",
    continue: "继续",
    deleteProgress: "删除进度",
    noStoriesCreated: "您还没有创作任何故事。",
    createFirstStory: "创作你的第一个冒险吧！",
    noGamesPlayed: "您还没有玩过任何故事。",
    findAStory: "找一个故事来玩吧！",
    dialogueWindowOpacity: "对话窗口透明度",
    dialogueBubbleOpacity: "对话气泡透明度",
    // Dialogs
    discardChangesTitle: "要放弃更改吗？",
    discardChangesMessage: "您有未保存的更改。确定要退出吗？如果需要临时保存，可以先发布为“非公开”。",
    discard: "放弃",
    keepEditing: "继续编辑",
    deleteCardTitle: "删除资料卡？",
    deleteCardMessage: "您确定要永久删除此资料卡吗？此操作无法撤销。",
    delete: "删除",
    edit: "编辑",
    import: "导入",
    export: "导出",
    publishErrorTitle: "无法发布",
    publishErrorMessage: "发布前请填写标题、故事简介和开场白。",
    restartGameTitle: "重新开始冒险？",
    restartGameMessage: "您确定要开始新游戏吗？您在此冒险中的当前进度将丢失。",
    restart: "重新开始",
    deleteStoryTitle: "删除故事？",
    deleteStoryMessage: "您确定要永久删除这个故事吗？所有保存的进度也将丢失。此操作无法撤销。",
    deletePlaythroughTitle: "删除进度？",
    deletePlaythroughMessage: "您确定要删除这个故事的保存进度吗？此操作无法撤销。",
  },
};

export const DEFAULT_PROMPTS = {
  en: {
    background: "A forgotten kingdom cursed with eternal twilight, where ancient ruins hide powerful artifacts.",
    character: "A disgraced knight seeking redemption, haunted by visions of a fallen queen.",
    openingMonologue: "You find yourself standing before the colossal, crumbling gates of a long-forgotten kingdom. An eternal twilight hangs in the sky, casting long, eerie shadows that seem to dance and writhe at the edge of your vision. The air is thick with the scent of damp earth, decay, and a faint, almost imperceptible hum of ancient magic. Before you lies a path into darkness and mystery. What secrets does this cursed land hold? What destiny awaits you within its shadowed heart? Your adventure is about to begin.",
    openingAction: "Start a new adventure game in a dark fantasy world. Provide the opening scene.",
  },
  zh: {
    background: "一个被永恒黄昏诅咒的被遗忘的王国，古老的废墟中隐藏着强大的神器。",
    character: "一位寻求救赎的蒙羞骑士，被一位堕落女王的幻象所困扰。",
    openingMonologue: "你发现自己站在一个早已被遗忘的王国那巨大而摇摇欲坠的城门前。永恒的黄昏悬挂在天际，投下长而诡异的阴影，它们仿佛在你视线的边缘舞蹈、扭动。空气中弥漫着潮湿泥土、腐朽和一丝微弱到几乎无法察觉的古老魔法的嗡鸣。你面前是一条通往黑暗与神秘的道路。这片被诅咒的土地隐藏着什么秘密？在那阴影笼罩的中心，又有什么样的命运在等待着你？你的冒险，即将开始。",
    openingAction: "开始一个黑暗幻想世界的文字冒险游戏。请提供开场场景。",
  }
};

export const DEFAULT_SETTINGS: GameSettings = {
  provider: 'gemini',
  customEndpoint: '',
  customApiKey: '',
  customModelId: '',
  useJsonSchemaForCustom: false,
  lmStudioCompatibleJson: false,
  enableImageGeneration: true,
  language: 'en',
  theme: 'dark',
  uiScale: 100,
  dialogueWindowOpacity: 100,
  bubbleOpacity: 100,
  llm: {
    temperature: 0.8,
    topP: 0.95,
    topK: 40,
    maxOutputTokens: 2048,
    frequencyPenalty: 0,
    presencePenalty: 0,
    autoMaxTokens: true,
    fetchedMaxTokens: null,
  },
  systemInstructions: [
    { id: simpleUUID(), title: 'Game Master Persona', role: 'system', text: 'You are an expert text adventure game master creating a rich, descriptive, and engaging world.', enabled: true },
    { id: simpleUUID(), title: 'Theme', role: 'system', text: 'The theme is dark fantasy. Avoid modern elements.', enabled: true },
  ],
};